#!/usr/bin/env ruby

require 'yaml'

HOME = ENV['HOME']
if not HOME then
	print "$HOME unknown. You must have it set\n"
	exit 1
end
CFG = HOME + "/.pathdude.yml"

if not File.exists?(CFG) then
	File.open(CFG, "w") do |f|
		f.write("commands:\n")
		f.write(" - git add\n")
		f.write(" - git rm -rf\n")
	end
end

g_config = []
File.open(CFG, "r") do |f|
	g_config = YAML.load(f.read())
end

g_files = []
ARGF.each do |line|
	chunks_raw = line.split(/[ \n\r\t]/)
	g_files += chunks_raw.select{ |f| File.exists?(f) }
end

g_config["commands"].each do |template|
	print "# #{template} {{{ \n"
	g_files.each do |fn|
		print "# #{template} #{fn}\n"
	end
	print "# }}} \n"
end
