#!/usr/bin/env ruby

require 'yaml'

HOME = ENV['HOME']
if not HOME then
	print "$HOME unknown. You must have it set\n"
	exit 1
end
CFG = HOME + "/.pathdude.yml"

only_abs = false
ARGV.each do |arg|
	if arg =~ /--only-absolute/ then
		only_abs = true
	end
end

if not File.exists?(CFG) then
	File.open(CFG, "w") do |f|
		f.write("commands:\n")
		f.write(" - git add\n")
		f.write(" - git rm -rf\n")
	end
end

g_config = []
File.open(CFG, "r") do |f|
	g_config = YAML.load(f.read())
end

g_files = []
while line = $stdin.gets
	chunks_raw = line.split(/[ \n\r\t]/)
	g_files += chunks_raw.select{ |f| File.exists?(f) }
end

if g_config["header"] then
	g_config["header"].each do |hdr|
		print "# " + hdr + "\n"
	end
end

print "# Path:\n"
g_files.each { |p| print "%s\n" % [File.realpath(p) ] }
exit 0 if only_abs

fst = true
g_config["commands"].each do |template|
	if not fst then
		print "\n\n# }}}\n"
	end
	fst = false
	print "# --------------- #{template} --------------------- {{{\n"
	g_files.each do |fn|
		print "# #{template} #{fn}\n"
	end
end
